"""update_reviews_check_constraints

Revision ID: 51ee5fbe6b5a
Revises: 6f9de4a2e86d
Create Date: 2026-05-03 20:36:26.382788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '51ee5fbe6b5a'
down_revision: Union[str, Sequence[str], None] = '6f9de4a2e86d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_reviews_plot_rating', 'reviews', 'plot_rating >= 1 AND plot_rating <= 10')
    op.create_check_constraint('ck_reviews_characters_rating', 'reviews', 'characters_rating >= 1 AND characters_rating <= 10')
    op.create_check_constraint('ck_reviews_style_rating', 'reviews', 'style_rating >= 1 AND style_rating <= 10')
    op.create_check_constraint('ck_reviews_pacing_rating', 'reviews', 'pacing_rating >= 1 AND pacing_rating <= 10')
    op.create_check_constraint('ck_reviews_world_rating', 'reviews', 'world_rating >= 1 AND world_rating <= 10')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_reviews_plot_rating', 'reviews', type_='check')
    op.drop_constraint('ck_reviews_characters_rating', 'reviews', type_='check')
    op.drop_constraint('ck_reviews_style_rating', 'reviews', type_='check')
    op.drop_constraint('ck_reviews_pacing_rating', 'reviews', type_='check')
    op.drop_constraint('ck_reviews_world_rating', 'reviews', type_='check')
    # ### end Alembic commands ###
