"""add updated_at to bookmarks

Revision ID: 6f9de4a2e86d
Revises: 417c9f309167
Create Date: 2026-04-30 15:47:27.478074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9de4a2e86d'
down_revision: Union[str, Sequence[str], None] = '417c9f309167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmarks', 'updated_at')
    # ### end Alembic commands ###
