"""add fields to user

Revision ID: a360791d2e93
Revises: 05b5d70695a0
Create Date: 2026-05-06 22:19:56.028021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a360791d2e93'
down_revision: Union[str, Sequence[str], None] = '05b5d70695a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=1024), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=1024), nullable=True))
    op.add_column('users', sa.Column('favorite_genres', postgresql.ARRAY(sa.String(length=100)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_genres')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
